export function createSeedDatabase() {
  const database = {
    meta: {
      version: 1,
      city: "Prayagraj",
      createdAt: "2026-07-25T00:00:00.000Z"
    },
    doctors: [
      {
        id: "d1",
        name: "Dr. Aditi Sharma",
        initials: "AS",
        specialty: "Dermatologist",
        specialization: "Dermatologist",
        qualification: "MD Dermatology, AIIMS",
        experience: 12,
        fee: 450,
        consultationFee: 450,
        rating: 4.9,
        reviews: 328,
        distance: 2.1,
        gender: "Female",
        languages: ["Hindi", "English"],
        availability: "Today",
        nextSlot: "5:30 PM",
        clinic: "Aura Skin & Laser Clinic",
        address: "Civil Lines, Prayagraj",
        location: "Civil Lines",
        avgWait: "12 min",
        verified: true,
        status: "verified",
        colors: ["#d9f8f0", "#bce9ff", "#155f59"],
        services: ["Acne care", "Hair fall", "Skin allergy", "Laser consultation"],
        education: "MBBS — KGMU · MD Dermatology — AIIMS New Delhi"
      },
      {
        id: "d2",
        name: "Dr. Rohan Verma",
        initials: "RV",
        specialty: "Cardiologist",
        specialization: "Cardiologist",
        qualification: "DM Cardiology, BHU",
        experience: 16,
        fee: 700,
        consultationFee: 700,
        rating: 4.8,
        reviews: 512,
        distance: 3.4,
        gender: "Male",
        languages: ["Hindi", "English", "Bhojpuri"],
        availability: "Tomorrow",
        nextSlot: "10:15 AM",
        clinic: "Pulse Heart Centre",
        address: "George Town, Prayagraj",
        location: "George Town",
        avgWait: "18 min",
        verified: true,
        status: "verified",
        colors: ["#dbeafe", "#c4d5ff", "#214c91"],
        services: ["Heart check-up", "ECG", "Hypertension", "Cardiac consultation"],
        education: "MBBS, MD Medicine — IMS BHU · DM Cardiology — SGPGI"
      },
      {
        id: "d3",
        name: "Dr. Nida Khan",
        initials: "NK",
        specialty: "Gynaecologist",
        specialization: "Gynaecologist",
        qualification: "MS Obstetrics & Gynae",
        experience: 9,
        fee: 500,
        consultationFee: 500,
        rating: 4.8,
        reviews: 276,
        distance: 4.2,
        gender: "Female",
        languages: ["Hindi", "English", "Urdu"],
        availability: "Today",
        nextSlot: "7:00 PM",
        clinic: "Nurture Women’s Clinic",
        address: "Lukerganj, Prayagraj",
        location: "Lukerganj",
        avgWait: "10 min",
        verified: true,
        status: "verified",
        colors: ["#fae8ff", "#e3ccff", "#71347c"],
        services: ["Women’s health", "Pregnancy care", "PCOS", "Routine check-up"],
        education: "MBBS — AMU · MS Obstetrics & Gynaecology — MAMC"
      },
      {
        id: "d4",
        name: "Dr. Kabir Singh",
        initials: "KS",
        specialty: "Orthopaedic",
        specialization: "Orthopaedic",
        qualification: "MS Orthopaedics",
        experience: 14,
        fee: 550,
        consultationFee: 550,
        rating: 4.7,
        reviews: 410,
        distance: 5.6,
        gender: "Male",
        languages: ["Hindi", "English"],
        availability: "Today",
        nextSlot: "6:15 PM",
        clinic: "Motion Bone & Joint",
        address: "Tagore Town, Prayagraj",
        location: "Tagore Town",
        avgWait: "16 min",
        verified: true,
        status: "verified",
        colors: ["#fef3c7", "#d7f0db", "#516642"],
        services: ["Joint pain", "Sports injury", "Fracture care", "Physiotherapy"],
        education: "MBBS — MLN Medical College · MS Orthopaedics — KGMU"
      },
      {
        id: "d5",
        name: "Dr. Meera Joshi",
        initials: "MJ",
        specialty: "Paediatrician",
        specialization: "Paediatrician",
        qualification: "MD Paediatrics",
        experience: 11,
        fee: 400,
        consultationFee: 400,
        rating: 4.9,
        reviews: 389,
        distance: 6.1,
        gender: "Female",
        languages: ["Hindi", "English"],
        availability: "Tomorrow",
        nextSlot: "9:30 AM",
        clinic: "Little Steps Child Care",
        address: "Naini, Prayagraj",
        location: "Naini",
        avgWait: "9 min",
        verified: true,
        status: "verified",
        colors: ["#e0f2fe", "#c7f9ee", "#225b70"],
        services: ["Child wellness", "Vaccination", "Nutrition", "Newborn care"],
        education: "MBBS — GSVM Kanpur · MD Paediatrics — KGMU"
      },
      {
        id: "d6",
        name: "Dr. Arjun Malhotra",
        initials: "AM",
        specialty: "General Physician",
        specialization: "General Physician",
        qualification: "MD Internal Medicine",
        experience: 8,
        fee: 350,
        consultationFee: 350,
        rating: 4.6,
        reviews: 198,
        distance: 1.8,
        gender: "Male",
        languages: ["Hindi", "English"],
        availability: "Today",
        nextSlot: "4:45 PM",
        clinic: "CareFirst Clinic",
        address: "Katra, Prayagraj",
        location: "Katra",
        avgWait: "8 min",
        verified: true,
        status: "verified",
        colors: ["#d1fae5", "#bfdbfe", "#155e75"],
        services: ["Fever & flu", "Diabetes", "General health", "Follow-up"],
        education: "MBBS — SN Medical College · MD Medicine — RML Lucknow"
      },
      {
        id: "d7",
        name: "Dr. Sana Rahman",
        initials: "SR",
        specialty: "ENT Specialist",
        specialization: "ENT Specialist",
        qualification: "MS ENT",
        experience: 7,
        fee: 400,
        consultationFee: 400,
        rating: 0,
        reviews: 0,
        distance: 3.8,
        gender: "Female",
        languages: ["Hindi", "English", "Urdu"],
        availability: "Pending verification",
        nextSlot: "—",
        clinic: "HearWell Clinic",
        address: "Allahpur, Prayagraj",
        location: "Allahpur",
        avgWait: "—",
        verified: false,
        status: "pending",
        colors: ["#e9d5ff", "#cffafe", "#6b21a8"],
        services: ["ENT consultation"],
        education: "Verification documents under review"
      }
    ],
    labs: [
      {
        id: "l1",
        name: "HealthSure Diagnostics",
        location: "Civil Lines",
        address: "Civil Lines, Prayagraj",
        rating: 4.8,
        reviews: 680,
        distance: 1.6,
        certified: "NABL",
        accreditation: "NABL",
        homeCollection: true,
        reportTime: "6 hours",
        test: "Thyroid Profile (T3, T4, TSH)",
        price: 499,
        originalPrice: 750,
        discount: 33,
        nextSlot: "Today, 4:00 PM",
        verified: true,
        status: "verified",
        tests: [
          { id: "t1", name: "Thyroid Profile (T3, T4, TSH)", price: 499, reportTime: "6 hours" },
          { id: "t2", name: "Complete Blood Count (CBC)", price: 299, reportTime: "4 hours" },
          { id: "t3", name: "HbA1c", price: 399, reportTime: "8 hours" }
        ]
      },
      {
        id: "l2",
        name: "CityCare PathLabs",
        location: "George Town",
        address: "George Town, Prayagraj",
        rating: 4.7,
        reviews: 522,
        distance: 2.8,
        certified: "NABL",
        accreditation: "NABL",
        homeCollection: true,
        reportTime: "8 hours",
        test: "Thyroid Profile (T3, T4, TSH)",
        price: 449,
        originalPrice: 699,
        discount: 36,
        nextSlot: "Today, 5:30 PM",
        verified: true,
        status: "verified",
        tests: [
          { id: "t4", name: "Thyroid Profile (T3, T4, TSH)", price: 449, reportTime: "8 hours" },
          { id: "t5", name: "Vitamin D", price: 799, reportTime: "12 hours" }
        ]
      },
      {
        id: "l3",
        name: "Prima Diagnostics",
        location: "Tagore Town",
        address: "Tagore Town, Prayagraj",
        rating: 4.6,
        reviews: 301,
        distance: 4.5,
        certified: "ISO",
        accreditation: "ISO",
        homeCollection: false,
        reportTime: "4 hours",
        test: "Thyroid Profile (T3, T4, TSH)",
        price: 575,
        originalPrice: 700,
        discount: 18,
        nextSlot: "Tomorrow, 7:00 AM",
        verified: true,
        status: "verified",
        tests: [
          { id: "t6", name: "Thyroid Profile (T3, T4, TSH)", price: 575, reportTime: "4 hours" },
          { id: "t7", name: "Complete Blood Count (CBC)", price: 249, reportTime: "3 hours" }
        ]
      },
      {
        id: "l4",
        name: "Apollo Health Check",
        location: "Naini",
        address: "Naini, Prayagraj",
        rating: 4.9,
        reviews: 917,
        distance: 6.2,
        certified: "NABL",
        accreditation: "NABL",
        homeCollection: true,
        reportTime: "12 hours",
        test: "Full Body Essential Package",
        price: 1299,
        originalPrice: 2299,
        discount: 43,
        nextSlot: "Tomorrow, 6:30 AM",
        verified: true,
        status: "verified",
        tests: [
          { id: "t8", name: "Full Body Essential Package", price: 1299, reportTime: "12 hours" },
          { id: "t9", name: "Lipid Profile", price: 499, reportTime: "8 hours" }
        ]
      },
      {
        id: "l5",
        name: "Nova Precision Labs",
        location: "Kareli",
        address: "Kareli, Prayagraj",
        rating: 0,
        reviews: 0,
        distance: 5.2,
        certified: "NABL application",
        accreditation: "Pending",
        homeCollection: true,
        reportTime: "8 hours",
        test: "Complete Blood Count (CBC)",
        price: 275,
        originalPrice: 350,
        discount: 21,
        nextSlot: "After verification",
        verified: false,
        status: "pending",
        tests: [{ id: "t10", name: "Complete Blood Count (CBC)", price: 275, reportTime: "8 hours" }]
      }
    ],
    bookings: [
      {
        id: "a1",
        patientId: "u1",
        patientName: "Abhigyan Kumar",
        doctorId: "d1",
        doctorName: "Dr. Aditi Sharma",
        date: "2026-07-26",
        day: "26",
        month: "Jul",
        time: "5:30 PM",
        type: "Clinic visit",
        status: "Confirmed",
        token: "A-18",
        currentToken: "A-14",
        ahead: 3,
        wait: 18,
        amount: 450,
        upcoming: true,
        createdAt: "2026-07-25T09:00:00.000Z"
      },
      {
        id: "a2",
        patientId: "u1",
        patientName: "Abhigyan Kumar",
        doctorId: "d4",
        doctorName: "Dr. Kabir Singh",
        date: "2026-07-30",
        day: "30",
        month: "Jul",
        time: "11:15 AM",
        type: "Clinic visit",
        status: "Confirmed",
        amount: 550,
        upcoming: true,
        createdAt: "2026-07-24T10:20:00.000Z"
      },
      {
        id: "a3",
        patientId: "u1",
        patientName: "Abhigyan Kumar",
        doctorId: "d6",
        doctorName: "Dr. Arjun Malhotra",
        date: "2026-07-10",
        day: "10",
        month: "Jul",
        time: "4:00 PM",
        type: "Clinic visit",
        status: "Completed",
        amount: 350,
        upcoming: false,
        createdAt: "2026-07-09T13:00:00.000Z"
      }
    ],
    users: [
      { id: "u1", name: "Abhigyan Kumar", phone: "+91 98765 43021", bookings: 3, lastActive: "2 min ago", status: "active" },
      { id: "u2", name: "Riya Sinha", phone: "+91 91234 56102", bookings: 2, lastActive: "12 min ago", status: "active" },
      { id: "u3", name: "Imran Ali", phone: "+91 99881 22034", bookings: 7, lastActive: "1 hour ago", status: "active" },
      { id: "u4", name: "Neha Gupta", phone: "+91 88990 11442", bookings: 3, lastActive: "Yesterday", status: "active" }
    ],
    reports: [
      { id: "r1", patientId: "u1", name: "Complete Blood Count", lab: "HealthSure Diagnostics", date: "22 Jul 2026", type: "Lab report", size: "1.8 MB" },
      { id: "r2", patientId: "u1", name: "Consultation Prescription", lab: "Dr. Arjun Malhotra", date: "10 Jul 2026", type: "Prescription", size: "620 KB" },
      { id: "r3", patientId: "u1", name: "Thyroid Profile", lab: "CityCare PathLabs", date: "28 Jun 2026", type: "Lab report", size: "1.2 MB" },
      { id: "r4", patientId: "u1", name: "Vitamin D & B12", lab: "Prima Diagnostics", date: "14 Jun 2026", type: "Lab report", size: "980 KB" }
    ],
    notifications: [
      { id: "n1", title: "Your turn is getting closer", copy: "Only 3 patients ahead of you at Aura Skin & Laser Clinic.", message: "Only 3 patients ahead of you at Aura Skin & Laser Clinic.", time: "2 min ago", icon: "activity", unread: true, audience: "Queue patients", createdAt: "2026-07-25T15:58:00.000Z" },
      { id: "n2", title: "Appointment confirmed", copy: "Dr. Kabir Singh confirmed your visit for 30 July at 11:15 AM.", message: "Dr. Kabir Singh confirmed your visit for 30 July at 11:15 AM.", time: "1 hour ago", icon: "check-circle", unread: true, audience: "Single patient", createdAt: "2026-07-25T15:00:00.000Z" },
      { id: "n3", title: "New report uploaded", copy: "Your Complete Blood Count report is ready to view.", message: "Your Complete Blood Count report is ready to view.", time: "22 Jul", icon: "file", unread: false, audience: "Single patient", createdAt: "2026-07-22T12:00:00.000Z" }
    ],
    queues: {
      d1: {
        doctorId: "d1",
        status: "live",
        currentToken: "A-12",
        current: { token: "A12", name: "Riya Sharma", age: 31, reason: "Skin allergy review", appointmentId: "apt-1003" },
        waiting: [
          { token: "A13", name: "Nisha Gupta", wait: 6, reason: "Pigmentation", appointmentId: "apt-1004" },
          { token: "A14", name: "Vikram Rao", wait: 19, reason: "Eczema follow-up", appointmentId: "apt-1005" },
          { token: "A15", name: "Aarav Mehta", wait: 32, reason: "Acne consultation", appointmentId: null },
          { token: "A16", name: "Simran Kaur", wait: 45, reason: "Hair fall", appointmentId: null },
          { token: "A17", name: "Kabir Malhotra", wait: 58, reason: "Rash and itching", appointmentId: "apt-1006" },
          { token: "A18", name: "Ananya Bose", wait: 71, reason: "Hair care", appointmentId: "apt-1007" }
        ],
        seen: 13,
        averageMinutes: 14,
        expectedMinutes: 15,
        elapsedSeconds: 504,
        delayMinutes: 0,
        updatedAt: "2026-07-25T16:00:00.000Z"
      }
    },
    doctorWorkspace: {
      doctorId: "d1",
      dashboard: {
        metrics: [
          { label: "Today’s appointments", value: "21", trend: "+3 vs avg.", icon: "calendar", tone: "mint" },
          { label: "Total patients", value: "1,284", trend: "+8.6%", icon: "users", tone: "blue" },
          { label: "Pending requests", value: "3", trend: "Needs review", icon: "clock", tone: "amber" },
          { label: "Today’s earnings", value: "₹12.4k", trend: "+11.2%", icon: "rupee", tone: "violet" }
        ]
      },
      appointments: [
        { id: "apt-1001", time: "09:00", period: "AM", name: "Meera Sethi", age: 34, gender: "Female", phone: "98110 23418", token: "A08", reason: "Acne follow-up", type: "Follow-up", status: "completed", note: "Continue current routine for four weeks." },
        { id: "apt-1002", time: "10:30", period: "AM", name: "Arjun Verma", age: 27, gender: "Male", phone: "98990 31267", token: "A09", reason: "Hair fall consultation", type: "New patient", status: "completed", note: "" },
        { id: "apt-1003", time: "01:00", period: "PM", name: "Riya Sharma", age: 31, gender: "Female", phone: "99580 65012", token: "A12", reason: "Skin allergy review", type: "Follow-up", status: "in-progress", note: "" },
        { id: "apt-1004", time: "01:30", period: "PM", name: "Nisha Gupta", age: 42, gender: "Female", phone: "99102 78431", token: "A13", reason: "Pigmentation", type: "New patient", status: "confirmed", note: "" },
        { id: "apt-1005", time: "02:00", period: "PM", name: "Vikram Rao", age: 38, gender: "Male", phone: "98721 14496", token: "A14", reason: "Eczema follow-up", type: "Follow-up", status: "confirmed", note: "" },
        { id: "apt-1006", time: "04:30", period: "PM", name: "Kabir Malhotra", age: 24, gender: "Male", phone: "98188 63108", token: "A17", reason: "Rash and itching", type: "New patient", status: "pending", note: "" },
        { id: "apt-1007", time: "05:15", period: "PM", name: "Ananya Bose", age: 29, gender: "Female", phone: "98919 45723", token: "A18", reason: "Hair care consultation", type: "New patient", status: "pending", note: "" },
        { id: "apt-1008", time: "06:15", period: "PM", name: "Dev Khanna", age: 45, gender: "Male", phone: "98208 12764", token: "A19", reason: "Psoriasis review", type: "Follow-up", status: "pending", note: "" }
      ],
      patients: [
        { id: "p-01", name: "Riya Sharma", phone: "99580 65012", age: 31, gender: "Female", lastVisit: "Today", visits: 6, concern: "Skin allergy", status: "Regular", tone: "mint", history: [{ date: "25 Jul 2026", concern: "Skin allergy review" }, { date: "08 May 2026", concern: "Contact dermatitis" }] },
        { id: "p-02", name: "Meera Sethi", phone: "98110 23418", age: 34, gender: "Female", lastVisit: "Today", visits: 4, concern: "Acne", status: "Follow-up due", tone: "violet", history: [{ date: "25 Jul 2026", concern: "Acne follow-up" }, { date: "12 Jun 2026", concern: "Acne consultation" }] },
        { id: "p-03", name: "Arjun Verma", phone: "98990 31267", age: 27, gender: "Male", lastVisit: "Today", visits: 2, concern: "Hair fall", status: "Regular", tone: "blue", history: [{ date: "25 Jul 2026", concern: "Hair fall consultation" }] },
        { id: "p-04", name: "Nisha Gupta", phone: "99102 78431", age: 42, gender: "Female", lastVisit: "18 Jul 2026", visits: 5, concern: "Pigmentation", status: "Follow-up due", tone: "amber", history: [{ date: "18 Jul 2026", concern: "Pigmentation review" }] }
      ],
      profile: {
        id: "d1",
        name: "Dr. Aditi Sharma",
        specialisation: "Dermatologist",
        phone: "+91 98765 12345",
        registrationNumber: "UPMC-2014-48291",
        clinic: "Aura Skin & Laser Clinic",
        address: "Civil Lines, Prayagraj",
        languages: ["Hindi", "English"],
        availability: [
          { day: "Monday", enabled: true, from: "09:00", to: "18:30" },
          { day: "Tuesday", enabled: true, from: "09:00", to: "18:30" },
          { day: "Wednesday", enabled: true, from: "10:00", to: "19:00" },
          { day: "Thursday", enabled: true, from: "09:00", to: "18:30" },
          { day: "Friday", enabled: true, from: "09:00", to: "18:30" },
          { day: "Saturday", enabled: true, from: "09:00", to: "14:00" },
          { day: "Sunday", enabled: false, from: "09:00", to: "13:00" }
        ],
        holidays: [
          { id: "h-1", date: "15 Aug 2026", label: "Independence Day" },
          { id: "h-2", date: "27 Aug 2026", label: "Personal leave" }
        ],
        services: [
          { id: "s-1", name: "Clinic consultation", fee: 700, duration: "15 min" },
          { id: "s-2", name: "Follow-up consultation", fee: 500, duration: "10 min" },
          { id: "s-3", name: "Skin procedure consultation", fee: 900, duration: "20 min" },
          { id: "s-4", name: "Hair & scalp assessment", fee: 800, duration: "20 min" }
        ]
      },
      analytics: {
        totalBookings: 426,
        repeatPatients: "64%",
        revenue: "₹2.84L",
        rating: "4.9",
        cancellationRate: "4.2%"
      }
    }
  };
  database.doctors = [];
  return database;
}
